///////////////////////////////////////////////////////////
//  FacilityManager.cs
//  Implementation of the Class FacilityManager
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2019 9:09:09 AM
//  Original author: USER
package Bean;


public interface FacilityManager {

    static FacilityManager instance = null;
    public Item item = null;
    public Court court = null;


    public void createInstance(String facType);

    public FacilityManager getInstance();
}