///////////////////////////////////////////////////////////
//  FacilityManager.cs
//  Implementation of the Class FacilityManager
//  Generated by Enterprise Architect
//  Created on:      15-Apr-2019 9:09:09 AM
//  Original author: USER


package Bean;

	abstract class FacilityManager implements Facility{

		public FacilityManager instance;
		public Item item;
		public Court court;

		public FacilityManager(){

		}

		public void CreateInstance(String facType){

			if(facType.equals("Court"))
                        {
                            court = new Court();
                        }
                        else if(facType.equals("Item"))
                         {
                            item = new Item();
                        }  
                       
		}

		public FacilityManager getInstance(){

			return instance;
		}

}//end FacilityManager

